name: Compile PDFs

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: thomasweise/texlive

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build files 1
        run: make cv resume

      # Second build required to get \LastPage labels defined
      - name: Build files 2
        run: make cv resume

      - name: Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Release
        uses: softprops/action-gh-release@v1
        permissions:
          contents: write
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: *.pdf
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
          tag_name: ${{ steps.version.outputs.version }}
          generate_release_notes: true