name: Compile PDFs

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: thomasweise/texlive

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create output dir
        run: mkdir output

      - name: Build files 1
        run: make cv resume

      # Second build required to get \LastPage labels defined
      - name: Build files 2
        run: make cv resume

      - name: Debug files
        run: ls -alhR

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ca-central-1'
          SOURCE_DIR: 'output'