name: Compile PDFs

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: thomasweise/texlive
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build files 1
        run: make cv resume

      # Second build required to get \LastPage labels defined
      - name: Build files 2
        run: make cv resume

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor

      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cv.pdf
            resume.pdf
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true
